#!/usr/bin/env python3
"""Wall-clock comparison: Ciphey (Rust, this repo) vs Python Ciphey 5.14.0 on identical inputs.

* Rust ciphey runs with `-d` (no y/N prompt) and a fresh $HOME per run, so its SQLite
  result cache can never answer for it.
* Python Ciphey runs with `-g` (print only the answer). Runs that exceed PY_TIMEOUT
  are recorded as "did not finish".
* Every run's answer is compared with the known plaintext.
* Every run is wrapped in `timeout 60` (coreutils), so nothing can run away.

Setup used for the numbers in results.json:
    python3 -m venv /tmp/pyciphey && /tmp/pyciphey/bin/pip install ciphey==5.14.0
    cargo build --release
    python3 media/tui-video/bench/bench_compare.py

Env: RUST_CIPHEY, PY_CIPHEY, N (Rust runs per input, default 10), PY_N (default 3),
     PY_TIMEOUT (seconds, default and maximum 60), OUT (results JSON path).

`--js-only` skips the runs and just rewrites ../video/bench.js from results.json
(the Fast clip reads its numbers from there).
"""
import base64
import binascii
import codecs
import json
import os
import platform
import re
import shutil
import statistics
import subprocess
import sys
import tempfile
import time
import urllib.parse

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
RUST = os.environ.get("RUST_CIPHEY", os.path.join(ROOT, "target", "release", "ciphey"))
PY_CIPHEY = os.environ.get("PY_CIPHEY", "/tmp/pyciphey/bin/ciphey")
CFG = os.path.join(HERE, "..", "capture", "config-capptucin.toml")
N = int(os.environ.get("N", "10"))
PY_N = int(os.environ.get("PY_N", "3"))
PY_TIMEOUT = min(int(os.environ.get("PY_TIMEOUT", "60")), 60)
OUT = os.environ.get("OUT", os.path.join(HERE, "results.json"))
BENCH_JS = os.path.join(HERE, "..", "video", "bench.js")

ENC = {
    "base64": lambda s: base64.b64encode(s.encode()).decode(),
    "base32": lambda s: base64.b32encode(s.encode()).decode(),
    "hex": lambda s: binascii.hexlify(s.encode()).decode(),
    "rot13": lambda s: codecs.encode(s, "rot13"),
    "url": lambda s: urllib.parse.quote(s, safe=""),
}
# (label, plaintext, encodings applied in order: the last one is the outer layer)
CASES = [
    ("Base64", "Hello, World! This is a test of ciphey.", ["base64"]),
    ("Hex → Base64", "The quick brown fox jumps over the lazy dog", ["hex", "base64"]),
    ("ROT13 → Hex → Base64 (the Fast clip)", "Ciphey is very fast", ["rot13", "hex", "base64"]),
    ("URL → Base64 → Hex", "The quick brown fox jumps over the lazy dog", ["url", "base64", "hex"]),
    ("Base64 ×4", "Ciphey peels back every layer of encoding", ["base64"] * 4),
    ("Hex → Base32 → Base64 → Hex", "Ciphey cracks this in milliseconds", ["hex", "base32", "base64", "hex"]),
    ("ROT13 → Hex → Base64 → Base32", "Ciphey cracks this in milliseconds", ["rot13", "hex", "base64", "base32"]),
]
ANSI = re.compile(r"\x1b\[[0-9;]*m")


def run_rust(ct):
    home = tempfile.mkdtemp(prefix="bench-ciphey-")
    os.makedirs(os.path.join(home, ".ciphey"))
    shutil.copy(CFG, os.path.join(home, ".ciphey", "config.toml"))
    try:
        t0 = time.perf_counter()
        p = subprocess.run(["timeout", "60", RUST, "-d", "-t", ct], capture_output=True, text=True,
                           env={**os.environ, "HOME": home})
        dt = time.perf_counter() - t0
    finally:
        shutil.rmtree(home, ignore_errors=True)
    lines = [ln for ln in ANSI.sub("", p.stdout).splitlines() if ln.strip()]
    got = lines[lines.index("The plaintext is:") + 1] if "The plaintext is:" in lines else None
    return dt, got


def run_python(ct, home):
    t0 = time.perf_counter()
    p = subprocess.run(["timeout", str(PY_TIMEOUT), PY_CIPHEY, "-g", "-t", ct], capture_output=True, text=True,
                       env={**os.environ, "HOME": home})
    dt = time.perf_counter() - t0
    if p.returncode == 124:  # killed by timeout: no answer within PY_TIMEOUT
        return None, None
    out = ANSI.sub("", p.stdout).strip().splitlines()
    return dt, (out[-1].strip() if out else None)


def write_js():
    with open(OUT, encoding="utf-8") as fh:
        data = json.load(fh)
    with open(BENCH_JS, "w", encoding="utf-8") as fh:
        fh.write("// GENERATED by bench/bench_compare.py from bench/results.json. Do not edit by hand.\n")
        fh.write("window.CIPHEY_BENCH = " + json.dumps(data, ensure_ascii=False) + ";\n")
    print("wrote", BENCH_JS)


def main():
    if "--js-only" in sys.argv:
        return write_js()
    py_home = tempfile.mkdtemp(prefix="bench-pyciphey-")
    py_version = subprocess.run([os.path.join(os.path.dirname(PY_CIPHEY), "python"), "-c",
                                 "import importlib.metadata as m; print(m.version('ciphey'))"],
                                capture_output=True, text=True).stdout.strip()
    # The commit of the checkout the binary was built in (RUST_CIPHEY may point at another clone).
    rev = subprocess.run(["git", "-C", os.path.dirname(os.path.abspath(RUST)), "rev-parse", "--short", "HEAD"],
                         capture_output=True, text=True).stdout.strip()
    meta = {
        "date_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "ciphey_rust_commit": rev,
        "python_ciphey_version": py_version,
        "machine": f"{platform.machine()}, {os.cpu_count()} logical CPUs, {platform.system()} {platform.release()}",
        "cpus": os.cpu_count(),
        "load_average_start": os.getloadavg(),
        "rust_runs_per_input": N, "python_runs_per_input": PY_N, "python_timeout_s": PY_TIMEOUT,
    }
    rows = []
    for label, plaintext, chain in CASES:
        ct = plaintext
        for enc in chain:
            ct = ENC[enc](ct)
        rust = [run_rust(ct) for _ in range(N)]
        py, dnf = [], False
        for _ in range(PY_N):
            dt, got = run_python(ct, py_home)
            if dt is None:
                dnf = True
                break
            py.append((dt, got))
        row = {
            "input": label, "layers": len(chain), "ciphertext": ct, "plaintext": plaintext,
            "rust_median_s": round(statistics.median(d for d, _ in rust), 3),
            "rust_runs_s": [round(d, 3) for d, _ in rust],
            "rust_correct": all(g == plaintext for _, g in rust),
            "python_median_s": None if dnf else round(statistics.median(d for d, _ in py), 3),
            "python_runs_s": [round(d, 3) for d, _ in py],
            "python_correct": None if dnf else all(g == plaintext for _, g in py),
            "python_did_not_finish_within_s": PY_TIMEOUT if dnf else None,
        }
        rows.append(row)
        py_txt = f"did not finish in {PY_TIMEOUT}s" if dnf else \
            f"{row['python_median_s']:.2f}s ({'correct' if row['python_correct'] else 'WRONG answer'})"
        print(f"{label:40s} rust {row['rust_median_s']:.2f}s ({'correct' if row['rust_correct'] else 'WRONG'})"
              f" | python {py_txt}", flush=True)
    meta["load_average_end"] = os.getloadavg()
    shutil.rmtree(py_home, ignore_errors=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        json.dump({"meta": meta, "results": rows}, fh, indent=1, ensure_ascii=False)
        fh.write("\n")
    print("wrote", OUT)
    write_js()


if __name__ == "__main__":
    sys.exit(main())
