//! Decode Base32 written with one of the other common alphabets: base32hex, Crockford's
//! Base32 and z-base-32.
//!
//! Everything but the table of 32 symbols is ordinary Base32: 5 bits per symbol, 8 symbols
//! to 5 bytes, so a text of 1, 3 or 6 symbols past a multiple of 8 can't be decoded.
//!
//! | Key | Symbols 0 to 31 | Notes |
//! |---|---|---|
//! | `base32hex` | `0-9A-V` | RFC 4648 §7, DNSSEC NSEC3. Either case, optional `=` padding |
//! | `Crockford` | `0-9A-HJKMNP-TV-Z` | ULIDs. Either case, `O` is `0`, `I` and `L` are `1`, `-` is ignored |
//! | `z-base-32` | `ybndrfg8ejkmcpqxot1uwisza345h769` | Tahoe-LAFS, ZRTP. Lower case only |
//!
//! Standard Base32 (`A-Z2-7`) belongs to the Base32 decoder.
//!
//! Every alphabet is tried. Output that isn't printable ASCII is dropped, and the rest is
//! checked in the order above. The alphabet is reported as the key.
//!
//! References: <https://datatracker.ietf.org/doc/html/rfc4648#section-7>,
//! <https://www.crockford.com/base32.html>,
//! <https://philzimmermann.com/docs/human-oriented-base-32-encoding.txt>.

use crate::checkers::CheckerTypes;
use crate::decoders::interface::check_string_success;
use data_encoding::{Encoding, Specification, BASE32HEX_NOPAD};
use once_cell::sync::Lazy;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{debug, trace};

/// The Base32 Variants decoder, call:
/// `let base32_variants_decoder = Decoder::<Base32VariantsDecoder>::new()` to create a new instance
/// And then call:
/// `result = base32_variants_decoder.crack(input)` to decode Base32 with another alphabet
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::base32_variants_decoder::Base32VariantsDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_base32_variants = Decoder::<Base32VariantsDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_base32_variants.crack(
///     "AHK6A83HELKM6QP0C9P6UTRE41J6UU10D9QMQS3J41NNCPBI41Q6GP90DHGNKU90CHNME===",
///     &checker,
/// );
/// assert!(result.success);
/// assert_eq!(
///     result.unencrypted_text.unwrap()[0],
///     "The quick brown fox jumps over the lazy dog"
/// );
/// assert_eq!(result.key.as_deref(), Some("base32hex"));
/// ```
pub struct Base32VariantsDecoder;

/// Shorter text decodes to printable junk too often. 8 symbols are 5 bytes.
const MIN_LEN: usize = 8;

impl Crack for Decoder<Base32VariantsDecoder> {
    fn new() -> Decoder<Base32VariantsDecoder> {
        Decoder {
            name: "Base32 Variants",
            description: "Base32 with another alphabet than RFC 4648's standard one: base32hex (RFC 4648 §7), Crockford's Base32 and z-base-32; the alphabet is reported as the key.",
            link: "https://en.wikipedia.org/wiki/Base32#Alternative_versions",
            tags: vec!["base32", "base32_variants", "decoder", "base"],
            popularity: 0.3,
            phantom: std::marker::PhantomData,
        }
    }

    /// Decodes `text` with every alphabet that fits it. Returns the first candidate the
    /// checker identifies, or else all of them for the search to decode further.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Base32 Variants with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());
        let candidates = decode_variants(text);
        if candidates.is_empty() {
            debug!("Base32 Variants found no alphabet that decodes the text to printable ASCII");
            return results;
        }

        for (alphabet, candidate) in &candidates {
            let checker_result = checker.check(candidate);
            if checker_result.is_identified {
                results.unencrypted_text = Some(vec![candidate.clone()]);
                results.update_checker(&checker_result);
                results.key = Some(alphabet.to_string());
                return results;
            }
        }

        let alphabets: Vec<&str> = candidates.iter().map(|(alphabet, _)| *alphabet).collect();
        results.key = Some(alphabets.join(", "));
        results.unencrypted_text = Some(candidates.into_iter().map(|(_, text)| text).collect());
        results
    }

    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// base32hex in either case, without padding
static BASE32HEX: Lazy<Encoding> = Lazy::new(|| {
    let mut spec = BASE32HEX_NOPAD.specification();
    spec.translate.from.push_str("abcdefghijklmnopqrstuv");
    spec.translate.to.push_str("ABCDEFGHIJKLMNOPQRSTUV");
    spec.encoding().unwrap()
});

/// Crockford's Base32 in either case, with `O`, `I` and `L` read as digits and `-` skipped
static CROCKFORD: Lazy<Encoding> = Lazy::new(|| {
    let mut spec = Specification::new();
    spec.symbols.push_str("0123456789ABCDEFGHJKMNPQRSTVWXYZ");
    spec.translate.from.push_str("abcdefghjkmnpqrstvwxyzOoIiLl");
    spec.translate.to.push_str("ABCDEFGHJKMNPQRSTVWXYZ001111");
    spec.ignore.push('-');
    spec.encoding().unwrap()
});

/// z-base-32, lower case only
static Z_BASE_32: Lazy<Encoding> = Lazy::new(|| {
    let mut spec = Specification::new();
    spec.symbols.push_str("ybndrfg8ejkmcpqxot1uwisza345h769");
    spec.encoding().unwrap()
});

/// Decodes `text` with `encoding` and returns it if every byte is printable ASCII, a tab or
/// a line break.
fn decode_printable(encoding: &Encoding, text: &[u8]) -> Option<String> {
    let bytes = encoding.decode(text).ok()?;
    if !bytes
        .iter()
        .all(|&byte| matches!(byte, b' '..=b'~' | b'\t' | b'\n' | b'\r'))
    {
        return None;
    }
    String::from_utf8(bytes).ok()
}

/// Decodes `text` with every alphabet, and returns the alphabet name and the text of each
/// decoding that is printable ASCII. Nothing is checked.
fn decode_variants(text: &str) -> Vec<(&'static str, String)> {
    let text = text.trim();
    if text.len() < MIN_LEN {
        return Vec::new();
    }
    // Only base32hex has padding, and like the Base32 decoder it takes any amount of it
    let unpadded = text.trim_end_matches('=');
    let alphabets: [(&'static str, &Encoding, &str); 3] = [
        ("base32hex", &BASE32HEX, unpadded),
        ("Crockford", &CROCKFORD, text),
        ("z-base-32", &Z_BASE_32, text),
    ];
    alphabets
        .into_iter()
        .filter_map(|(name, encoding, text)| {
            let decoded = decode_printable(encoding, text.as_bytes())?;
            check_string_success(&decoded, text).then_some((name, decoded))
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::{decode_variants, Base32VariantsDecoder};
    use crate::{
        checkers::{
            athena::Athena,
            checker_type::{Check, Checker},
            CheckerTypes,
        },
        decoders::{
            crack_results::CrackResult,
            interface::{Crack, Decoder},
        },
        filtration_system::get_decoder_by_name,
    };

    // The three issue examples (#921) were made with Python's base64.b32hexencode, npm
    // base32-encode's Crockford variant and an implementation of the z-base-32 spec. The
    // others are Python's base64.b32encode with str.translate onto the alphabet.

    const SPHINX: &str = "Sphinx of black quartz, judge my vow.";
    const FOX: &str = "The quick brown fox jumps over the lazy dog";

    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    fn crack(text: &str) -> CrackResult {
        Decoder::<Base32VariantsDecoder>::new().crack(text, &get_athena_checker())
    }

    fn assert_cracked(text: &str, plaintext: &str, key: &str) {
        let result = crack(text);
        assert!(result.success, "{text:?} was not identified: {result:?}");
        assert_eq!(
            result.unencrypted_text.as_deref(),
            Some(&[plaintext.to_string()][..])
        );
        assert_eq!(result.key.as_deref(), Some(key), "{text:?}");
    }

    fn assert_no_candidate(text: &str) {
        assert_eq!(decode_variants(text), Vec::new(), "{text:?}");
        let result = crack(text);
        assert!(result.unencrypted_text.is_none(), "{text:?}: {result:?}");
        assert!(!result.success);
    }

    #[test]
    fn issue_examples_decode() {
        // The Athena checker doesn't accept this pangram, so the search gets it as a
        // candidate instead
        assert_eq!(
            decode_variants("ADO6GQBEF0G6UPH0C9M62ORB41ONAOBIEHT2O83AELI6EP90DLSI0TJFESN0===="),
            [("base32hex", SPHINX.to_string())]
        );
        assert_eq!(
            decode_variants("ADR6GTBEF0G6YSH0C9P62RVB41RQARBJEHX2R83AENJ6ES90DNWJ0XKFEWQ0"),
            [("Crockford", SPHINX.to_string())]
        );
        assert_eq!(
            decode_variants("kpago4mqxyog63tycjsgna5mrbazkam1qt7naedkqi1gq3jypih1y7uxqhzy"),
            [("z-base-32", SPHINX.to_string())]
        );
    }

    #[test]
    fn fox_in_each_alphabet() {
        assert_cracked(
            "AHK6A83HELKM6QP0C9P6UTRE41J6UU10D9QMQS3J41NNCPBI41Q6GP90DHGNKU90CHNME===",
            FOX,
            "base32hex",
        );
        assert_cracked(
            "AHM6A83HENMP6TS0C9S6YXVE41K6YY10D9TPTW3K41QQCSBJ41T6GS90DHGQMY90CHQPE",
            FOX,
            "Crockford",
        );
        assert_cracked(
            "ktwgkedtqiwsg43ycj3g675qrbug66bypj4s4hdurbzzc3m1rb4go3jyptozw6jyctzsq",
            FOX,
            "z-base-32",
        );
    }

    #[test]
    fn base32hex_in_lower_case_and_without_padding() {
        assert_cracked(
            "ahk6a83helkm6qp0c9p6utre41j6uu10d9qmqs3j41nncpbi41q6gp90dhgnku90chnme",
            FOX,
            "base32hex",
        );
    }

    #[test]
    fn crockford_aliases_and_hyphens() {
        // O is read as 0, I and L as 1, and the hyphens are skipped
        assert_cracked(
            "ahm6a83hen-mp6tsOc9s6-yxve4Ik6-yyI0d9tp-tw3k4Lqq-csbj4It6-gs90dhgq-my90chqpe",
            FOX,
            "Crockford",
        );
    }

    #[test]
    fn standard_base32_is_not_claimed() {
        assert_no_candidate("NBSWY3DPEB3W64TMMQ======");
        assert_no_candidate("KRUGS4ZANBQXGID2MVZG6IDQMFSGI2LOM4");
    }

    #[test]
    fn impossible_lengths_are_rejected() {
        // 9 symbols: one past a multiple of 8
        assert_no_candidate("ahk6a83he");
        assert_no_candidate("ktwgkedtq");
    }

    #[test]
    fn short_text_is_rejected() {
        // base32hex of "hell"
        assert_no_candidate("d1imor0");
        assert_no_candidate("hello");
    }

    #[test]
    fn handles_panic_if_empty_string() {
        assert_no_candidate("");
    }

    #[test]
    fn handles_panic_if_emoji() {
        assert_no_candidate("😂😂😂😂😂😂😂😂");
    }

    #[test]
    fn english_text_is_rejected() {
        assert_no_candidate("hello my name is panicky mc panic face!");
    }

    #[test]
    fn registered_once() {
        let decoders = get_decoder_by_name("Base32 Variants");
        assert_eq!(decoders.components.len(), 1);
        assert_eq!(decoders.components[0].get_name(), "Base32 Variants");
        assert!(crate::decoders::DECODER_MAP.contains_key("Base32 Variants"));
    }
}
