//! Decode a caesar cipher string
//! Performs error handling and returns a string
//! Call caesar_decoder.crack to use. It returns `Option<String>` and check with
//! `result.is_some()` to see if it returned okay.
//! Ranks all 25 shifts by English letter-pair fitness and only asks the checker (at Low
//! sensitivity) about the best one. With a `--regex` crib every shift is checked.

use crate::checkers::json_checker::is_json_object_or_array;
use crate::checkers::lemmeknow_checker::{is_marked_ctf_flag, is_unmarked_ctf_flag};
use crate::checkers::CheckerTypes;
use crate::config::get_config;
use crate::decoders::interface::{best_ranked, check_string_success};
use gibberish_or_not::Sensitivity;

use super::crack_results::CrackResult;
use super::interface::Crack;
use super::interface::Decoder;

use log::{info, trace};

/// The caesar decoder, call:
/// `let caesar_decoder = Decoder::<caesarDecoder>::new()` to create a new instance
/// And then call:
/// `result = caesar_decoder.crack(input)` to decode a caesar string
/// The struct generated by new() comes from interface.rs
/// ```
/// use ciphey::decoders::caesar_decoder::CaesarDecoder;
/// use ciphey::decoders::interface::{Crack, Decoder};
/// use ciphey::checkers::{athena::Athena, CheckerTypes, checker_type::{Check, Checker}};
///
/// let decode_caesar = Decoder::<CaesarDecoder>::new();
/// let athena_checker = Checker::<Athena>::new();
/// let checker = CheckerTypes::CheckAthena(athena_checker);
///
/// let result = decode_caesar.crack("uryyb guvf vf ybat grkg", &checker).unencrypted_text;
/// assert!(result.is_some());
/// // If it succeeds, the 0th element is the plaintext else it'll contain 25 elements
/// // of unsuccessfully decoded text
/// assert_eq!(result.unwrap()[0], "hello this is long text");
/// ```
pub struct CaesarDecoder;

impl Crack for Decoder<CaesarDecoder> {
    fn new() -> Decoder<CaesarDecoder> {
        Decoder {
            name: "caesar",
            description: "Caesar cipher, also known as Caesar's cipher, the shift cipher, Caesar's code or Caesar shift, is one of the simplest and most widely known encryption techniques. It is a type of substitution cipher in which each letter in the plaintext is replaced by a letter some fixed number of positions down the alphabet. Only the shift whose output looks most like English is checked, at Low sensitivity.",
            link: "https://en.wikipedia.org/wiki/Caesar_cipher",
            tags: vec!["caesar", "decryption", "classic", "reciprocal"],
            popularity: 0.8,
            phantom: std::marker::PhantomData,
        }
    }

    /// This function does the actual decoding
    /// It returns an `Option<String>` if it was successful
    /// Else the Option returns nothing and the error is logged in Trace
    ///
    /// Asking the checker about every shift and taking the first it accepts found wrong
    /// shifts that happen to look like words (`BYFFIQILFX` for `HELLOWORLD`). Only the
    /// most English-looking shift is checked now, so a wrong one is only returned if the
    /// right one isn't the best ranked.
    fn crack(&self, text: &str, checker: &CheckerTypes) -> CrackResult {
        trace!("Trying Caesar Cipher with text {:?}", text);
        let mut results = CrackResult::new(self, text.to_string());
        let decoded_strings: Vec<String> = (1..=25).map(|shift| caesar(text, shift)).collect();
        if !check_string_success(&decoded_strings[0], text) {
            info!(
                "Failed to decode caesar because check_string_success returned false on string {}. This means the string is 'funny' as it wasn't modified.",
                decoded_strings[0]
            );
            return results;
        }

        // With a crib every shift is checked: the crib says which one is right.
        // Otherwise a shift that gives a CTF flag (`picoCTF{...}`) goes first, since a
        // flag's contents are often hex or random letters and the right shift needn't
        // rank best, then the best-ranked shift.
        let to_check: Vec<usize> = if get_config().regex.is_some() {
            (0..decoded_strings.len()).collect()
        } else if is_json_object_or_array(text) {
            // A shift keeps JSON's shape, so every shift would pass as JSON
            Vec::new()
        } else {
            let flag = decoded_strings
                .iter()
                .position(|text| is_marked_ctf_flag(text));
            let best = best_ranked(decoded_strings.iter().map(String::as_str));
            let mut to_check: Vec<usize> = flag.into_iter().chain(best).collect();
            to_check.dedup();
            // A shift keeps a flag's shape, so only a flag word in the prefix says this
            // shift is the right one
            to_check.retain(|&index| !is_unmarked_ctf_flag(&decoded_strings[index]));
            to_check
        };
        let checker_with_sensitivity = checker.with_sensitivity(Sensitivity::Low);
        for index in to_check {
            let checker_result = checker_with_sensitivity.check(&decoded_strings[index]);
            if checker_result.is_identified {
                let shift = index + 1;
                trace!("Found a match with caesar shift {}", shift);
                results.unencrypted_text = Some(vec![decoded_strings[index].clone()]);
                results.update_checker(&checker_result);
                results.key = Some(shift.to_string());
                return results;
            }
        }
        results.unencrypted_text = Some(decoded_strings);
        results
    }
    /// Gets all tags for this decoder
    fn get_tags(&self) -> &Vec<&str> {
        &self.tags
    }
    /// Gets the name for the current decoder
    fn get_name(&self) -> &str {
        self.name
    }
    /// Gets the popularity for the current decoder
    fn get_popularity(&self) -> f32 {
        self.popularity
    }
    /// Gets the description for the current decoder
    fn get_description(&self) -> &str {
        self.description
    }
    /// Gets the link for the current decoder
    fn get_link(&self) -> &str {
        self.link
    }
}

/// Caesar cipher to rotate cipher text by shift and return an owned String.
fn caesar(cipher: &str, shift: u8) -> String {
    cipher
        .chars()
        .map(|c| {
            if c.is_ascii_alphabetic() {
                let first = if c.is_ascii_lowercase() { b'a' } else { b'A' };
                // modulo the distance to keep character range
                (first + (c as u8 + shift - first) % 26) as char
            } else {
                c
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::CaesarDecoder;
    use super::*;
    use crate::{
        checkers::{
            athena::Athena,
            checker_type::{Check, Checker},
            english::EnglishChecker,
            CheckerTypes,
        },
        decoders::interface::{Crack, Decoder},
    };

    // helper for tests
    fn get_athena_checker() -> CheckerTypes {
        let athena_checker = Checker::<Athena>::new();
        CheckerTypes::CheckAthena(athena_checker)
    }

    #[test]
    fn empty() {
        assert_eq!(caesar("", 13), "");
    }

    #[test]
    fn caesar_rot_13() {
        assert_eq!(caesar("rust", 13), "ehfg");
    }

    #[test]
    fn caesar_unicode() {
        assert_eq!(caesar("attack at dawn 攻", 5), "fyyfhp fy ifbs 攻");
    }

    #[test]
    fn successful_decoding() {
        let caesar_decoder = Decoder::<CaesarDecoder>::new();
        let result = caesar_decoder.crack("fyyfhp", &get_athena_checker());
        assert_eq!(result.unencrypted_text.unwrap()[0], "attack");
    }

    #[test]
    fn successful_decoding_correct_key() {
        let caesar_decoder = Decoder::<CaesarDecoder>::new();
        let result = caesar_decoder.crack("fyyfhp", &get_athena_checker());
        let key = result.key.expect("No key found for caesar cipher");
        assert_eq!(key, "21");
    }

    #[test]
    fn successful_decoding_one_step_forward() {
        let caesar_decoder = Decoder::<CaesarDecoder>::new();

        let result = caesar_decoder.crack("buubdl", &get_athena_checker());
        let decoded_str = &result
            .unencrypted_text
            .expect("No unencrypted text for caesar");
        assert_eq!(decoded_str[0], "attack");
    }

    #[test]
    fn successful_decoding_one_step_forward_correct_key() {
        let caesar_decoder = Decoder::<CaesarDecoder>::new();

        let result = caesar_decoder.crack("buubdl", &get_athena_checker());
        let key = result.key.expect("No key found for caesar cipher");
        assert_eq!(key, "25");
    }

    #[test]
    fn successful_decoding_one_step_backward() {
        let caesar_decoder = Decoder::<CaesarDecoder>::new();

        let result = caesar_decoder.crack("zsszbj", &get_athena_checker());
        let decoded_str = &result
            .unencrypted_text
            .expect("No unencrypted text for caesar");
        assert_eq!(decoded_str[0], "attack");
    }

    #[test]
    fn successful_decoding_one_step_backward_correct_key() {
        let caesar_decoder = Decoder::<CaesarDecoder>::new();

        let result = caesar_decoder.crack("zsszbj", &get_athena_checker());
        let key = result.key.expect("No key found for caesar cipher");
        assert_eq!(key, "1");
    }

    #[test]
    fn successful_decoding_longer_text() {
        let caesar_decoder = Decoder::<CaesarDecoder>::new();
        let result = caesar_decoder.crack(
            "Tqxxa ftue ue mz qjmybxq fqjf tffbe://saasxq.oay !",
            &get_athena_checker(),
        );
        println!("Result: {:?}", result);
        assert_eq!(
            result.unencrypted_text.unwrap()[0],
            "Hello this is an example text https://google.com !"
        );
    }

    #[test]
    fn successful_decoding_longer_text_correct_key() {
        let caesar_decoder = Decoder::<CaesarDecoder>::new();
        let result = caesar_decoder.crack(
            "Tqxxa ftue ue mz qjmybxq fqjf tffbe://saasxq.oay !",
            &get_athena_checker(),
        );
        let key = result.key.expect("No key found for caesar cipher");
        assert_eq!(key, "14");
    }

    #[test]
    fn successful_decoding_longer_text_with_puncuation() {
        let caesar_decoder = Decoder::<CaesarDecoder>::new();
        let result = caesar_decoder.crack(
            "Itk, tqxxa ftqdq. Ftue ue mz qjmybxq ar xazs fqjf iuft bgzogmfuaz!",
            &get_athena_checker(),
        );
        assert_eq!(
            result.unencrypted_text.unwrap()[0],
            "Why, hello there. This is an example of long text with puncuation!"
        );
    }

    #[test]
    fn successful_decoding_longer_text_with_puncuation_correct_key() {
        let caesar_decoder = Decoder::<CaesarDecoder>::new();
        let result = caesar_decoder.crack(
            "Itk, tqxxa ftqdq. Ftue ue mz qjmybxq ar xazs fqjf iuft bgzogmfuaz!",
            &get_athena_checker(),
        );
        let key = result.key.expect("No key found for caesar cipher");
        assert_eq!(key, "14");
    }

    #[test]
    fn caesar_decode_empty_string() {
        // caesar returns an empty string, this is a valid caesar string
        // but returns False on check_string_success
        let caesar_decoder = Decoder::<CaesarDecoder>::new();
        let result = caesar_decoder
            .crack("", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn caesar_decode_fails() {
        let caesar_decoder = Decoder::<CaesarDecoder>::new();
        let result = caesar_decoder
            .crack("#", &get_athena_checker())
            .unencrypted_text;
        assert!(result.is_none());
    }

    #[test]
    fn wrong_shifts_that_look_like_words_are_not_returned() {
        // https://github.com/bee-san/Ciphey/issues/1031: the first accepted shift used to
        // win, so KHOORZRUOG came back as BYFFIQILFX (an "ASIN") instead of HELLOWORLD
        let caesar_decoder = Decoder::<CaesarDecoder>::new();
        let result = caesar_decoder.crack("KHOORZRUOG", &get_athena_checker());
        assert!(result.success);
        assert_eq!(result.unencrypted_text.unwrap()[0], "HELLOWORLD");
        assert_eq!(result.key.as_deref(), Some("23"));

        let result =
            caesar_decoder.crack("WKHTXLFNEURZQIRAMXPSVRYHUWKHODCBGRJ", &get_athena_checker());
        assert_eq!(
            result.unencrypted_text.unwrap()[0],
            "THEQUICKBROWNFOXJUMPSOVERTHELAZYDOG"
        );

        let result = caesar_decoder.crack("dwwdfn dw gdzq", &get_athena_checker());
        assert_eq!(result.unencrypted_text.unwrap()[0], "attack at dawn");
    }

    #[test]
    fn flags_are_found_even_if_their_shift_does_not_rank_best() {
        // The hex contents make other shifts rank better by letter pairs
        let caesar_decoder = Decoder::<CaesarDecoder>::new();
        for (encoded, flag) in [
            ("synt{q41p3o8n9r2s5n6p}", "flag{d41c3b8a9e2f5a6c}"),
            ("cvpbPGS{7r1o9r3n2s4q}", "picoCTF{7e1b9e3a2f4d}"),
            ("synt{guvf_vf_gur_synt}", "flag{this_is_the_flag}"),
        ] {
            let result = caesar_decoder.crack(encoded, &get_athena_checker());
            assert!(result.success, "{encoded}");
            assert_eq!(result.unencrypted_text.unwrap()[0], flag);
        }
    }

    #[test]
    fn all_shifts_are_returned_when_none_is_plaintext() {
        let caesar_decoder = Decoder::<CaesarDecoder>::new();
        let result = caesar_decoder.crack("Xq7 zr9 Lk2 vbn", &get_athena_checker());
        assert!(!result.success);
        assert_eq!(result.unencrypted_text.unwrap().len(), 25);
    }

    #[test]
    fn caesar_works_with_the_english_checker() {
        let caesar_decoder = Decoder::<CaesarDecoder>::new();
        let result = caesar_decoder.crack(
            "Test text",
            &CheckerTypes::CheckEnglish(Checker::<EnglishChecker>::new()),
        );
        assert!(
            result.unencrypted_text.is_some(),
            "Caesar decoder should return some result"
        );
    }
}
