// Generated by ../capture/to_session_js.py from the recordings in ../capture/out/. Do not edit.
window.CIPHEY_MCP_SESSION = {
  "client": "kiro-cli 2.21.3",
  "recorded": "2026-10-01T17:43:18Z",
  "server": {
    "name": "ciphey",
    "version": "0.12.1"
  },
  "protocolVersion": "2025-11-25",
  "tools": [
    "decode",
    "list_decoders"
  ],
  "question": "I found this string in a CTF challenge. Can you decode it?",
  "ciphertext": "NzM3OTZlNzQ3YjcwNzY2Mzc1NzI2YzVmNjY2MzcyNmU3ODY2NWY3YTcwNjM3ZA==",
  "toolName": "decode",
  "arguments": {
    "text": "NzM3OTZlNzQ3YjcwNzY2Mzc1NzI2YzVmNjY2MzcyNmU3ODY2NWY3YTcwNjM3ZA=="
  },
  "result": {
    "checker": "LemmeKnow Checker",
    "path": [
      {
        "decoder": "Base64",
        "key": null
      },
      {
        "decoder": "Hexadecimal",
        "key": null
      },
      {
        "decoder": "caesar",
        "key": "13"
      }
    ],
    "plaintext": "flag{ciphey_speaks_mcp}",
    "status": "decoded",
    "timeout_secs": 10
  },
  "completedIn": "0.115s",
  "reply": [
    [
      [
        "text",
        "Decoded: "
      ],
      [
        "code",
        "flag{ciphey_speaks_mcp}"
      ]
    ],
    [
      [
        "text",
        "It was three layers: Base64 → hex → ROT13 (Caesar shift 13). The intermediate was "
      ],
      [
        "code",
        "synt{pvcurl_fcrnxf_zpc}"
      ],
      [
        "text",
        ", which is the flag under ROT13."
      ]
    ]
  ],
  "layers": [
    "NzM3OTZlNzQ3YjcwNzY2Mzc1NzI2YzVmNjY2MzcyNmU3ODY2NWY3YTcwNjM3ZA==",
    "73796e747b70766375726c5f6663726e78665f7a70637d",
    "synt{pvcurl_fcrnxf_zpc}",
    "flag{ciphey_speaks_mcp}"
  ],
  "decoderCount": 24,
  "install": "cargo install ciphey --features mcp --bin ciphey-mcp",
  "kiroAdd": "kiro-cli mcp add --name ciphey --command ciphey-mcp",
  "config": "{\n  \"mcpServers\": {\n    \"ciphey\": {\n      \"command\": \"ciphey-mcp\",\n      \"args\": []\n    }\n  }\n}"
};
